name: Hello world workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "HEllo sridhar"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye sridhar
        run: echo "goodbye Sridhar"
        shell: bash  